FROM node:24.12.0-bullseye

WORKDIR /usr/src/app

RUN corepack enable && corepack prepare yarn@1.22.22 --activate

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

CMD ["yarn", "start"]
