/**
 * @jest-environment node
 *
 * Characterization tests for server.js's /api/deleteSubmission route: real
 * HTTP through the actual express app, against a real Parse Server 2.8.4
 * backed by a real MongoDB 4.4 started in-memory by mongodb-memory-server, so
 * the full express/Parse query path is exercised. These lock in the handler's
 * current behavior so the deletion logic can later be extracted from
 * server.js without changing what the route does.
 */

import http from 'http';
import net from 'net';

import Parse from 'parse/node';

const { MongoMemoryServer } = require('mongodb-memory-server');
// parse-server is deliberately installed on demand instead of being a project
// dependency (see jest.globalSetup.js)
const { ParseServer } = require('parse-server');

// chunk-manifest.json is generated by the webpack build and doesn't exist
// in the test environment; server.js only needs it to exist at import time.
jest.mock('./chunk-manifest.json', () => ({}), { virtual: true });

// parse-server skips its cloud/URL verification (and test-unfriendly process
// listeners) when TESTING is set. Must be set before it is constructed.
process.env.TESTING = '1';

jest.setTimeout(30000);

const email = 'test@example.com';
const password = 'test-password';
const Submission = Parse.Object.extend('submission');

describe('/api/deleteSubmission', () => {
  let mongo;
  let parseServer;
  let httpServer;
  let baseUrl;
  let ownedSubmission;
  let iosStyleSubmission;
  let otherUsersSubmission;

  beforeAll(async () => {
    // MongoDB 4.4 is the newest version whose wire protocol parse-server
    // 2.8.4's bundled mongodb driver can talk to. Note: the binary must be
    // downloaded once (mongodb-memory-server caches it), and on Ubuntu 24+
    // mongod 4.4 needs libssl1.1 installed.
    mongo = await MongoMemoryServer.create({ binary: { version: '4.4.14' } });

    // create() can resolve a moment before mongod accepts connections;
    // parse-server connects to it in its constructor, so wait until the
    // port actually accepts a TCP connection.
    const { port } = new URL(mongo.getUri());
    const attemptConnection = (resolve, reject, attempts) => {
      const socket = net.connect(Number(port), '127.0.0.1');
      socket.once('connect', () => {
        socket.destroy();
        resolve();
      });
      socket.once('error', () => {
        socket.destroy();
        if (attempts < 100) {
          setTimeout(
            () => attemptConnection(resolve, reject, attempts + 1),
            50,
          );
        } else {
          reject(new Error('mongod never accepted connections'));
        }
      });
    };
    await new Promise((resolve, reject) => {
      attemptConnection(resolve, reject, 0);
    });

    parseServer = ParseServer.start(
      {
        databaseURI: mongo.getUri(),
        appId: 'test-app',
        masterKey: 'test-master',
        // Only used as a placeholder; the client points at the real port.
        serverURL: 'http://localhost/parse',
        mountPath: '/parse',
        port: 0,
        verbose: false,
        // server.js's logIn() throws its "check your email" error for users
        // without emailVerified, which the test server would otherwise
        // leave false after signup.
        verifyUserEmails: false,
      },
      () => {},
    );
    await new Promise((resolve, reject) => {
      parseServer.server.once('listening', resolve);
      parseServer.server.once('error', reject);
    });

    // server.js reads its config from env vars at import time, so point
    // them at the test server before requiring it. (The dotenv preload
    // doesn't override variables that are already set.)
    process.env.PARSE_APP_ID = 'test-app';
    process.env.PARSE_JAVASCRIPT_KEY = 'test-js-key';
    process.env.PARSE_MASTER_KEY = 'test-master';
    process.env.PARSE_SERVER_URL = `http://localhost:${parseServer.server.address().port}/parse`;
    process.env.HEROKU_RELEASE_VERSION = 'v123';

    // server.js calls app.listen(config.port) in a deferred microtask at
    // import time, which would bind a real port and leak the handle.
    // Replace listen (synchronously, before that microtask runs) with one
    // that listens on port 0 and captures the server.
    // eslint-disable-next-line global-require
    const app = require('./server.js').default;
    let listeningResolve;
    const listeningPromise = new Promise(resolve => {
      listeningResolve = resolve;
    });
    app.listen = (listenPort, callback) => {
      httpServer = http.createServer(app);
      httpServer.listen(0, () => {
        listeningResolve();
        if (callback) callback();
      });
      return httpServer;
    };
    await listeningPromise;
    baseUrl = `http://127.0.0.1:${httpServer.address().port}`;

    // server.js's import initialized our shared Parse client, so the test
    // user can be created directly against the test server. Parse Server
    // 2.8.4 leaves emailVerified unset even with verifyUserEmails: false,
    // and server.js's logIn() throws its "check your email" error for
    // unverified users, so mark the user verified explicitly.
    const user = new Parse.User();
    user.setUsername(email);
    user.set('email', email);
    user.setPassword(password);
    await user.signUp();
    user.set('emailVerified', true);
    await user.save(null, { sessionToken: user.getSessionToken() });

    ownedSubmission = new Submission();
    ownedSubmission.set('Username', email);
    ownedSubmission.set('timeofreport', new Date('2026-09-03T15:00:00.000Z'));
    await ownedSubmission.save();

    // iOS submissions don't always have Username set; getSubmissions()
    // matches them by the "email" field instead.
    iosStyleSubmission = new Submission();
    iosStyleSubmission.set('email', email);
    iosStyleSubmission.set(
      'timeofreport',
      new Date('2026-09-03T14:00:00.000Z'),
    );
    await iosStyleSubmission.save();

    otherUsersSubmission = new Submission();
    otherUsersSubmission.set('Username', 'other@example.com');
    otherUsersSubmission.set(
      'timeofreport',
      new Date('2026-09-03T13:00:00.000Z'),
    );
    await otherUsersSubmission.save();
  });

  afterAll(async () => {
    // Guard each step so a beforeAll failure doesn't cascade into teardown.
    if (httpServer) {
      await new Promise(resolve => httpServer.close(resolve));
    }
    if (parseServer) {
      await new Promise(resolve => parseServer.server.close(resolve));
      parseServer.handleShutdown();
    }
    if (mongo) {
      await mongo.stop();
    }
  });

  const postDeleteSubmission = async objectId => {
    const response = await fetch(`${baseUrl}/api/deleteSubmission`, {
      method: 'POST',
      // force-ssl-heroku redirects requests that aren't https
      headers: { 'X-Forwarded-Proto': 'https' },
      // The route's saveUser() requires these profile fields, like the
      // client's form always sends them.
      body: new URLSearchParams({
        email,
        password,
        FirstName: 'Test',
        LastName: 'User',
        Phone: '5551234567',
        testify: 'true',
        objectId,
      }),
    });
    const body = await response.json();
    return { status: response.status, body };
  };

  test('deletes the submission with the given objectId', async () => {
    const { status, body } = await postDeleteSubmission(ownedSubmission.id);

    expect(status).toBe(200);
    expect(body).toEqual({ objectId: ownedSubmission.id });

    // The submission is really gone from Parse.
    const query = new Parse.Query(Submission);
    await expect(query.get(ownedSubmission.id)).rejects.toMatchObject({
      code: 101,
    });
  });

  test('deletes iOS-style submissions matched by the email field', async () => {
    const { status, body } = await postDeleteSubmission(iosStyleSubmission.id);

    expect(status).toBe(200);
    expect(body).toEqual({ objectId: iosStyleSubmission.id });

    const query = new Parse.Query(Submission);
    await expect(query.get(iosStyleSubmission.id)).rejects.toMatchObject({
      code: 101,
    });
  });

  test('rejects deleting a submission someone else made', async () => {
    const { status, body } = await postDeleteSubmission(
      otherUsersSubmission.id,
    );

    // The handler's getSubmissions() only returns the current user's
    // submissions, so the objectId isn't found and assert() fails.
    expect(status).toBe(500);
    expect(body.error.code).toBe('ERR_ASSERTION');
    expect(body.error.expected).toBe(true);

    // The other user's submission is still there.
    const query = new Parse.Query(Submission);
    const stillThere = await query.get(otherUsersSubmission.id);
    expect(stillThere.id).toBe(otherUsersSubmission.id);
  });
});
