/**
 * @jest-environment node
 *
 * Characterization tests for server.js's /submit route attachment handling:
 * real HTTP through the actual express app, against a real Parse Server
 * 2.8.4 backed by a real MongoDB 4.4 started in-memory by
 * mongodb-memory-server, so the full express/multer/Parse path is
 * exercised. These lock in the handler's current behavior so the
 * attachment-data preparation can later be extracted from server.js without
 * changing what the route does.
 */

import http from 'http';
import net from 'net';

import Parse from 'parse/node';

const { MongoMemoryServer } = require('mongodb-memory-server');
// parse-server is deliberately installed on demand instead of being a project
// dependency (see jest.globalSetup.js)
const { ParseServer } = require('parse-server');

// chunk-manifest.json is generated by the webpack build and doesn't exist
// in the test environment; server.js only needs it to exist at import time.
jest.mock('./chunk-manifest.json', () => ({}), { virtual: true });

// parse-server skips its cloud/URL verification (and test-unfriendly process
// listeners) when TESTING is set. Must be set before it is constructed.
process.env.TESTING = '1';

jest.setTimeout(30000);

// In-memory stand-in for a files adapter: the route under test only cares
// that Parse.File#save() succeeds and produces a URL, not where the bytes
// are stored, and the real GridStore adapter opens its own MongoDB
// connection that nothing shuts down (keeping the test process alive after
// the run).
class InMemoryFilesAdapter {
  constructor() {
    this.files = new Map();
  }

  createFile(filename, data) {
    this.files.set(filename, data);
    return Promise.resolve();
  }

  deleteFile(filename) {
    this.files.delete(filename);
    return Promise.resolve();
  }

  getFileData(filename) {
    return Promise.resolve(this.files.get(filename));
  }

  // eslint-disable-next-line class-methods-use-this
  getFileLocation(config, filename) {
    return `${config.mount}/files/${config.applicationId}/${encodeURIComponent(filename)}`;
  }
}

const email = 'test@example.com';
const password = 'test-password';

// Minimal 1x1 PNG, small enough to inline while still being recognized by
// the file-type detector.
const pngBuffer = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==',
  'base64',
);

describe('/submit attachment data', () => {
  let mongo;
  let parseServer;
  let httpServer;
  let baseUrl;

  beforeAll(async () => {
    // MongoDB 4.4 is the newest version whose wire protocol parse-server
    // 2.8.4's bundled mongodb driver can talk to. Note: the binary must be
    // downloaded once (mongodb-memory-server caches it), and on Ubuntu 24+
    // mongod 4.4 needs libssl1.1 installed.
    mongo = await MongoMemoryServer.create({ binary: { version: '4.4.14' } });

    // create() can resolve a moment before mongod accepts connections;
    // parse-server connects to it in its constructor, so wait until the
    // port actually accepts a TCP connection.
    const { port } = new URL(mongo.getUri());
    const attemptConnection = (resolve, reject, attempts) => {
      const socket = net.connect(Number(port), '127.0.0.1');
      socket.once('connect', () => {
        socket.destroy();
        resolve();
      });
      socket.once('error', () => {
        socket.destroy();
        if (attempts < 100) {
          setTimeout(
            () => attemptConnection(resolve, reject, attempts + 1),
            50,
          );
        } else {
          reject(new Error('mongod never accepted connections'));
        }
      });
    };
    await new Promise((resolve, reject) => {
      attemptConnection(resolve, reject, 0);
    });

    parseServer = ParseServer.start(
      {
        databaseURI: mongo.getUri(),
        appId: 'test-app',
        masterKey: 'test-master',
        // Only used as a placeholder; the client points at the real port.
        serverURL: 'http://localhost/parse',
        mountPath: '/parse',
        port: 0,
        verbose: false,
        // server.js's logIn() throws its "check your email" error for users
        // without emailVerified, which the test server would otherwise
        // leave false after signup.
        verifyUserEmails: false,
        filesAdapter: new InMemoryFilesAdapter(),
      },
      () => {},
    );
    await new Promise((resolve, reject) => {
      parseServer.server.once('listening', resolve);
      parseServer.server.once('error', reject);
    });

    // server.js reads its config from env vars at import time, so point
    // them at the test server before requiring it. (The dotenv preload
    // doesn't override variables that are already set.)
    process.env.PARSE_APP_ID = 'test-app';
    process.env.PARSE_JAVASCRIPT_KEY = 'test-js-key';
    process.env.PARSE_MASTER_KEY = 'test-master';
    process.env.PARSE_SERVER_URL = `http://localhost:${parseServer.server.address().port}/parse`;
    process.env.HEROKU_RELEASE_VERSION = 'v123';

    // server.js calls app.listen(config.port) in a deferred microtask at
    // import time, which would bind a real port and leak the handle.
    // Replace listen (synchronously, before that microtask runs) with one
    // that listens on port 0 and captures the server.
    // eslint-disable-next-line global-require
    const app = require('./server.js').default;
    let listeningResolve;
    const listeningPromise = new Promise(resolve => {
      listeningResolve = resolve;
    });
    app.listen = (listenPort, callback) => {
      httpServer = http.createServer(app);
      httpServer.listen(0, () => {
        listeningResolve();
        if (callback) callback();
      });
      return httpServer;
    };
    await listeningPromise;
    baseUrl = `http://127.0.0.1:${httpServer.address().port}`;

    // server.js's import initialized our shared Parse client, so the test
    // user can be created directly against the test server. Parse Server
    // 2.8.4 leaves emailVerified unset even with verifyUserEmails: false,
    // and server.js's logIn() throws its "check your email" error for
    // unverified users, so mark the user verified explicitly.
    const user = new Parse.User();
    user.setUsername(email);
    user.set('email', email);
    user.setPassword(password);
    await user.signUp();
    user.set('emailVerified', true);
    await user.save(null, { sessionToken: user.getSessionToken() });
  });

  afterAll(async () => {
    // Guard each step so a beforeAll failure doesn't cascade into teardown.
    if (httpServer) {
      await new Promise(resolve => httpServer.close(resolve));
    }
    if (parseServer) {
      await new Promise(resolve => parseServer.server.close(resolve));
      parseServer.handleShutdown();
    }
    if (mongo) {
      await mongo.stop();
    }
  });

  const submit = async ({ files = [], fields = {} }) => {
    const form = new FormData();
    // The route's saveUser() requires these profile fields, like the
    // client's form always sends them, and createSubmission() coerces the
    // strings to their final types.
    form.append('email', email);
    form.append('password', password);
    form.append('FirstName', 'Test');
    form.append('LastName', 'User');
    form.append('Phone', '5551234567');
    form.append('testify', 'true');
    form.append('plate', 'ABC1234');
    form.append('licenseState', 'NY');
    form.append('typeofreport', 'complaint');
    form.append('typeofcomplaint', 'Blocked the bike lane');
    form.append('reportDescription', 'Blocking the lane');
    form.append('can_be_shared_publicly', 'true');
    form.append('latitude', '40.7128');
    form.append('longitude', '-74.006');
    form.append('formatted_address', 'New York, NY');
    // A past timestamp, or createSubmission() rejects the submission.
    form.append(
      'CreateDate',
      new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    );
    Object.entries(fields).forEach(([key, value]) => form.append(key, value));
    files.forEach(file =>
      // multer's upload.array('attachmentData[]') matches this field name.
      form.append('attachmentData[]', new Blob([file.buffer]), file.filename),
    );

    const response = await fetch(`${baseUrl}/submit`, {
      method: 'POST',
      // force-ssl-heroku redirects requests that aren't https
      headers: { 'X-Forwarded-Proto': 'https' },
      body: form,
    });
    const body = await response.json();
    return { status: response.status, body };
  };

  const uploadAttachment = async buffer => {
    const form = new FormData();
    form.append('email', email);
    form.append('password', password);
    // The route's upload.single('attachmentData') matches this field name.
    form.append('attachmentData', new Blob([buffer]), 'photo.png');

    const response = await fetch(`${baseUrl}/api/uploadAttachment`, {
      method: 'POST',
      headers: { 'X-Forwarded-Proto': 'https' },
      body: form,
    });
    const body = await response.json();
    return { status: response.status, body };
  };

  test('creates a submission from directly-uploaded files', async () => {
    const { status, body } = await submit({
      files: [{ buffer: pngBuffer, filename: 'photo.png' }],
    });

    expect(status).toBe(200);
    expect(body.submission.photoData0).toMatchObject({
      __type: 'File',
      name: expect.stringMatching(/_photoData0\.png$/),
    });
  });

  test('creates a submission from pre-uploaded attachment ids', async () => {
    const upload = await uploadAttachment(pngBuffer);
    expect(upload.status).toBe(200);

    const { status, body } = await submit({
      fields: { attachmentIds: JSON.stringify([upload.body.id]) },
    });

    expect(status).toBe(200);
    expect(body.submission.photoData0).toMatchObject({
      __type: 'File',
      name: expect.stringMatching(/_photoData0\.png$/),
    });
  });

  test('rejects attachmentIds whose entries are not strings', async () => {
    const { status, body } = await submit({
      fields: { attachmentIds: JSON.stringify([123]) },
    });

    expect(status).toBe(500);
    expect(body.error.message).toBe('Invalid attachmentIds format');
  });

  test('rejects attachment ids that are not in the store', async () => {
    const { status, body } = await submit({
      fields: { attachmentIds: JSON.stringify(['a'.repeat(64)]) },
    });

    expect(status).toBe(500);
    expect(body.error.message).toBe(
      'Attachment not found; please re-add your files and try again',
    );
  });

  test('rejects malformed attachmentIds JSON with an empty error body', async () => {
    // The handler's "Invalid attachmentIds format" check only runs after
    // JSON.parse(), so malformed JSON surfaces the raw SyntaxError
    // instead; the client never sends this, but pin it anyway so the
    // extraction doesn't accidentally "fix" it. handlePromiseRejection
    // round-trips through json-stringify-safe, which keeps only
    // enumerable properties — and a SyntaxError has none — so the
    // response carries an empty error object.
    const { status, body } = await submit({
      fields: { attachmentIds: '[not json' },
    });

    expect(status).toBe(500);
    expect(body).toEqual({ error: {} });
  });
});
