/**
 * @jest-environment node
 *
 * Characterization tests for server.js's /api/uploadAttachment route: real
 * HTTP through the actual express app, against a real Parse Server 2.8.4
 * backed by a real MongoDB 4.4 started in-memory by
 * mongodb-memory-server, so the full multer/express/Parse log-in path is
 * exercised. These lock in the handler's current behavior so the attachment
 * logic can later be extracted from server.js without changing what the
 * route does. Files are written to the real temp-dir attachment store (see
 * src/attachmentStore.js).
 */

import crypto from 'crypto';
import http from 'http';
import net from 'net';

import Parse from 'parse/node';
import { readAttachment } from './attachmentStore.js';

const { MongoMemoryServer } = require('mongodb-memory-server');
// parse-server is deliberately installed on demand instead of being a project
// dependency (see jest.globalSetup.js)
const { ParseServer } = require('parse-server');

// chunk-manifest.json is generated by the webpack build and doesn't exist
// in the test environment; server.js only needs it to exist at import time.
jest.mock('./chunk-manifest.json', () => ({}), { virtual: true });

// parse-server skips its cloud/URL verification (and test-unfriendly process
// listeners) when TESTING is set. Must be set before it is constructed.
process.env.TESTING = '1';

jest.setTimeout(30000);

const email = 'test@example.com';
const password = 'test-password';

describe('/api/uploadAttachment', () => {
  let mongo;
  let parseServer;
  let httpServer;
  let baseUrl;

  const buffer = Buffer.from('attachment bytes');

  beforeAll(async () => {
    // MongoDB 4.4 is the newest version whose wire protocol parse-server
    // 2.8.4's bundled mongodb driver can talk to. Note: the binary must be
    // downloaded once (mongodb-memory-server caches it), and on Ubuntu 24+
    // mongod 4.4 needs libssl1.1 installed.
    mongo = await MongoMemoryServer.create({ binary: { version: '4.4.14' } });

    // create() can resolve a moment before mongod accepts connections;
    // parse-server connects to it in its constructor, so wait until the
    // port actually accepts a TCP connection.
    const { port } = new URL(mongo.getUri());
    const attemptConnection = (resolve, reject, attempts) => {
      const socket = net.connect(Number(port), '127.0.0.1');
      socket.once('connect', () => {
        socket.destroy();
        resolve();
      });
      socket.once('error', () => {
        socket.destroy();
        if (attempts < 100) {
          setTimeout(
            () => attemptConnection(resolve, reject, attempts + 1),
            50,
          );
        } else {
          reject(new Error('mongod never accepted connections'));
        }
      });
    };
    await new Promise((resolve, reject) => {
      attemptConnection(resolve, reject, 0);
    });

    parseServer = ParseServer.start(
      {
        databaseURI: mongo.getUri(),
        appId: 'test-app',
        masterKey: 'test-master',
        // Only used as a placeholder; the client points at the real port.
        serverURL: 'http://localhost/parse',
        mountPath: '/parse',
        port: 0,
        verbose: false,
        // server.js's logIn() throws its "check your email" error for users
        // without emailVerified, which the test server would otherwise
        // leave false after signup.
        verifyUserEmails: false,
      },
      () => {},
    );
    await new Promise((resolve, reject) => {
      parseServer.server.once('listening', resolve);
      parseServer.server.once('error', reject);
    });

    // server.js reads its config from env vars at import time, so point
    // them at the test server before requiring it. (The dotenv preload
    // doesn't override variables that are already set.)
    process.env.PARSE_APP_ID = 'test-app';
    process.env.PARSE_JAVASCRIPT_KEY = 'test-js-key';
    process.env.PARSE_MASTER_KEY = 'test-master';
    process.env.PARSE_SERVER_URL = `http://localhost:${parseServer.server.address().port}/parse`;
    process.env.HEROKU_RELEASE_VERSION = 'v123';

    // server.js calls app.listen(config.port) in a deferred microtask at
    // import time, which would bind a real port and leak the handle.
    // Replace listen (synchronously, before that microtask runs) with one
    // that listens on port 0 and captures the server.
    // eslint-disable-next-line global-require
    const app = require('./server.js').default;
    let listeningResolve;
    const listeningPromise = new Promise(resolve => {
      listeningResolve = resolve;
    });
    app.listen = (listenPort, callback) => {
      httpServer = http.createServer(app);
      httpServer.listen(0, () => {
        listeningResolve();
        if (callback) callback();
      });
      return httpServer;
    };
    await listeningPromise;
    baseUrl = `http://127.0.0.1:${httpServer.address().port}`;

    // server.js's import initialized our shared Parse client, so the test
    // user can be created directly against the test server. Parse Server
    // 2.8.4 leaves emailVerified unset even with verifyUserEmails: false,
    // and server.js's logIn() throws its "check your email" error for
    // unverified users, so mark the user verified explicitly.
    const user = new Parse.User();
    user.setUsername(email);
    user.set('email', email);
    user.setPassword(password);
    await user.signUp();
    user.set('emailVerified', true);
    await user.save(null, { sessionToken: user.getSessionToken() });
  });

  afterAll(async () => {
    // Guard each step so a beforeAll failure doesn't cascade into teardown.
    if (httpServer) {
      await new Promise(resolve => httpServer.close(resolve));
    }
    if (parseServer) {
      await new Promise(resolve => parseServer.server.close(resolve));
      parseServer.handleShutdown();
    }
    if (mongo) {
      await mongo.stop();
    }
  });

  const postAttachment = async ({ fields, file }) => {
    const formData = new FormData();
    Object.entries(fields).forEach(([key, value]) => {
      formData.append(key, String(value));
    });
    formData.append('attachmentData', new Blob([file]), 'attachment.txt');
    const response = await fetch(`${baseUrl}/api/uploadAttachment`, {
      method: 'POST',
      // force-ssl-heroku redirects requests that aren't https
      headers: { 'X-Forwarded-Proto': 'https' },
      body: formData,
    });
    const body = await response.json();
    return { status: response.status, body };
  };

  test('stores the file under its SHA-256 hash and returns that id', async () => {
    const { status, body } = await postAttachment({
      fields: { email, password },
      file: buffer,
    });

    expect(status).toBe(200);
    expect(body.id).toBe(
      crypto.createHash('sha256').update(buffer).digest('hex'),
    );
    expect(await readAttachment(body.id)).toEqual(buffer);
  });

  test('rejects a wrong password without storing anything', async () => {
    const neverWrittenBuffer = Buffer.from('never written');

    const { status, body } = await postAttachment({
      fields: { email, password: 'wrong-password' },
      file: neverWrittenBuffer,
    });

    expect(status).toBe(500);
    expect(body.error.code).toBe(101);

    const id = crypto
      .createHash('sha256')
      .update(neverWrittenBuffer)
      .digest('hex');
    expect(await readAttachment(id)).toBeNull();
  });
});
