/**
 * @jest-environment node
 *
 * Characterization tests for server.js's /api/logIn and /saveUser routes:
 * real HTTP through the actual express app, against a real Parse Server
 * 2.8.4 backed by a real MongoDB 4.4 started in-memory by
 * mongodb-memory-server, so the full express/Parse sign-up/log-in path is
 * exercised. These lock in the handlers' current behavior so the user logic
 * can later be extracted from server.js without changing what the routes do.
 */

import http from 'http';
import net from 'net';

import Parse from 'parse/node';

const { MongoMemoryServer } = require('mongodb-memory-server');
// parse-server is deliberately installed on demand instead of being a project
// dependency (see jest.globalSetup.js)
const { ParseServer } = require('parse-server');

// chunk-manifest.json is generated by the webpack build and doesn't exist
// in the test environment; server.js only needs it to exist at import time.
jest.mock('./chunk-manifest.json', () => ({}), { virtual: true });

// parse-server skips its cloud/URL verification (and test-unfriendly process
// listeners) when TESTING is set. Must be set before it is constructed.
process.env.TESTING = '1';

jest.setTimeout(30000);

const email = 'test@example.com';
const password = 'test-password';

describe('/api/logIn and /saveUser', () => {
  let mongo;
  let parseServer;
  let httpServer;
  let baseUrl;
  let verifiedUser;

  beforeAll(async () => {
    // MongoDB 4.4 is the newest version whose wire protocol parse-server
    // 2.8.4's bundled mongodb driver can talk to. Note: the binary must be
    // downloaded once (mongodb-memory-server caches it), and on Ubuntu 24+
    // mongod 4.4 needs libssl1.1 installed.
    mongo = await MongoMemoryServer.create({ binary: { version: '4.4.14' } });

    // create() can resolve a moment before mongod accepts connections;
    // parse-server connects to it in its constructor, so wait until the
    // port actually accepts a TCP connection.
    const { port } = new URL(mongo.getUri());
    const attemptConnection = (resolve, reject, attempts) => {
      const socket = net.connect(Number(port), '127.0.0.1');
      socket.once('connect', () => {
        socket.destroy();
        resolve();
      });
      socket.once('error', () => {
        socket.destroy();
        if (attempts < 100) {
          setTimeout(
            () => attemptConnection(resolve, reject, attempts + 1),
            50,
          );
        } else {
          reject(new Error('mongod never accepted connections'));
        }
      });
    };
    await new Promise((resolve, reject) => {
      attemptConnection(resolve, reject, 0);
    });

    parseServer = ParseServer.start(
      {
        databaseURI: mongo.getUri(),
        appId: 'test-app',
        masterKey: 'test-master',
        // Only used as a placeholder; the client points at the real port.
        serverURL: 'http://localhost/parse',
        mountPath: '/parse',
        port: 0,
        verbose: false,
        // server.js's logIn() throws its "check your email" error for users
        // without emailVerified, which the test server would otherwise
        // leave false after signup.
        verifyUserEmails: false,
      },
      () => {},
    );
    await new Promise((resolve, reject) => {
      parseServer.server.once('listening', resolve);
      parseServer.server.once('error', reject);
    });

    // server.js reads its config from env vars at import time, so point
    // them at the test server before requiring it. (The dotenv preload
    // doesn't override variables that are already set.)
    process.env.PARSE_APP_ID = 'test-app';
    process.env.PARSE_JAVASCRIPT_KEY = 'test-js-key';
    process.env.PARSE_MASTER_KEY = 'test-master';
    process.env.PARSE_SERVER_URL = `http://localhost:${parseServer.server.address().port}/parse`;
    process.env.HEROKU_RELEASE_VERSION = 'v123';

    // server.js calls app.listen(config.port) in a deferred microtask at
    // import time, which would bind a real port and leak the handle.
    // Replace listen (synchronously, before that microtask runs) with one
    // that listens on port 0 and captures the server.
    // eslint-disable-next-line global-require
    const app = require('./server.js').default;
    let listeningResolve;
    const listeningPromise = new Promise(resolve => {
      listeningResolve = resolve;
    });
    app.listen = (listenPort, callback) => {
      httpServer = http.createServer(app);
      httpServer.listen(0, () => {
        listeningResolve();
        if (callback) callback();
      });
      return httpServer;
    };
    await listeningPromise;
    baseUrl = `http://127.0.0.1:${httpServer.address().port}`;

    // server.js's import initialized our shared Parse client, so the test
    // user can be created directly against the test server. Parse Server
    // 2.8.4 leaves emailVerified unset even with verifyUserEmails: false,
    // and server.js's logIn() throws its "check your email" error for
    // unverified users, so mark the user verified explicitly.
    verifiedUser = new Parse.User();
    verifiedUser.setUsername(email);
    verifiedUser.set('email', email);
    verifiedUser.setPassword(password);
    await verifiedUser.signUp();
    verifiedUser.set('emailVerified', true);
    await verifiedUser.save(null, {
      sessionToken: verifiedUser.getSessionToken(),
    });
  });

  afterAll(async () => {
    // Guard each step so a beforeAll failure doesn't cascade into teardown.
    if (httpServer) {
      await new Promise(resolve => httpServer.close(resolve));
    }
    if (parseServer) {
      await new Promise(resolve => parseServer.server.close(resolve));
      parseServer.handleShutdown();
    }
    if (mongo) {
      await mongo.stop();
    }
  });

  const post = async ({ path, fields }) => {
    const response = await fetch(`${baseUrl}${path}`, {
      method: 'POST',
      // force-ssl-heroku redirects requests that aren't https
      headers: { 'X-Forwarded-Proto': 'https' },
      body: new URLSearchParams(fields),
    });
    const body = await response.json();
    return { status: response.status, body };
  };

  test('logs in an existing verified user', async () => {
    const { status, body } = await post({
      path: '/api/logIn',
      fields: { email, password },
    });

    expect(status).toBe(200);
    expect(body).toMatchObject({
      objectId: verifiedUser.id,
      username: email,
      email,
      emailVerified: true,
    });
  });

  test('refuses a user that signed up but has not verified their email', async () => {
    const { status, body } = await post({
      path: '/api/logIn',
      fields: { email: 'unverified@example.com', password },
    });

    expect(status).toBe(500);
    expect(body.error.message).toBe(
      'We just sent you an email with a link to confirm your address, please find and click that.',
    );
  });

  test('rejects a wrong password', async () => {
    const { status, body } = await post({
      path: '/api/logIn',
      fields: { email, password: 'wrong-password' },
    });

    expect(status).toBe(500);
    expect(body.error.code).toBe(101);
  });

  test('saves the profile fields onto the logged-in user', async () => {
    const { status, body } = await post({
      path: '/saveUser',
      fields: {
        email,
        password,
        FirstName: 'Test',
        LastName: 'User',
        Phone: '5551234567',
        testify: 'true',
      },
    });

    expect(status).toBe(200);
    expect(body).toMatchObject({
      objectId: verifiedUser.id,
      useremail: email,
      FirstName: 'Test',
      LastName: 'User',
      Phone: '5551234567',
      // The route stores the form value verbatim, and form fields arrive as
      // strings, so the saved value is the string 'true'.
      testify: 'true',
    });
  });

  test('rejects a save missing a required field', async () => {
    const { status, body } = await post({
      path: '/saveUser',
      fields: {
        email,
        password,
        FirstName: '',
        LastName: 'User',
        Phone: '5551234567',
        testify: 'true',
      },
    });

    expect(status).toBe(500);
    expect(body.error.message).toBe('FirstName is required');
  });
});
