name: Node.js CI - build --release

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.14.0]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.19
    - run: export PATH=$HOME/.yarn/bin:$PATH
    - run: yarn
    - run: yarn build --release
      env:
        CI: true
